"""initial migration

Revision ID: 7cb3baecfc2e
Revises: 
Create Date: 2023-12-30 10:47:11.330569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb3baecfc2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.String(length=30), nullable=True),
    sa.Column('ptype', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('footingid', sa.String(length=30), nullable=True),
    sa.Column('barmark', sa.String(length=20), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('spacing', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('no_of_bars', sa.Float(), nullable=False),
    sa.Column('cutting_length', sa.Float(), nullable=False),
    sa.Column('total_length', sa.Float(), nullable=False),
    sa.Column('unit_weight', sa.Float(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('footing')
    op.drop_table('project')
    # ### end Alembic commands ###
